# Generated by Django 5.0.7 on 2024-08-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('disiplina', models.CharField(max_length=50)),
                ('participantes', models.ManyToManyField(to='Persona.jugador')),
            ],
        ),
    ]
