# Generated by Django 5.0.7 on 2024-08-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('numeroEquipos', models.IntegerField()),
                ('numeroJugadores', models.IntegerField()),
                ('numeroArbitros', models.IntegerField()),
                ('tipo', models.CharField(choices=[('LI', 'Liga'), ('CO', 'Copa'), ('AM', 'Amistoso'), ('IN', 'Internacional'), ('MS', 'Muerte Súbita')], default='LI', max_length=2)),
            ],
        ),
    ]
