# Generated by Django 5.0.7 on 2024-08-03 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campeonato', '0001_initial'),
        ('Equipo', '0001_initial'),
        ('Persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('golesLocal', models.IntegerField()),
                ('golesVisitante', models.IntegerField()),
                ('resultado', models.CharField(choices=[('G', 'Ganado'), ('E', 'Empatado'), ('P', 'Perdido')], default='E', max_length=1)),
                ('arbitro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Persona.albitro')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campeonato.campeonato')),
                ('equipoLocal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_local', to='Equipo.equipo')),
                ('equipoVisitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_visitante', to='Equipo.equipo')),
            ],
        ),
    ]
