# Generated by Django 5.0.7 on 2024-08-03 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticasJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles', models.IntegerField()),
                ('tarjetasAmarillas', models.IntegerField()),
                ('tarjetasRojas', models.IntegerField()),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Persona.jugador')),
            ],
        ),
    ]
