# Generated by Django 5.0.7 on 2024-08-03 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipo', '0001_initial'),
        ('Estadisticas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticasEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partidosJugados', models.IntegerField()),
                ('partidosGanados', models.IntegerField()),
                ('partidosEmpatados', models.IntegerField()),
                ('partidosPerdidos', models.IntegerField()),
                ('golesFavor', models.IntegerField()),
                ('golesContra', models.IntegerField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipo.equipo')),
            ],
        ),
    ]
